server:
  port: ${SERVER_PORT:8080}
  
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379

fragment:
  storage:
    path: /app/fragments

central:
  service:
    url: ${CENTRAL_SERVICE_URL:http://centralservice:8080}

hostname: ${HOSTNAME:localhost}